### ISSUE TITLE
Can't save or play generated sequence

### ISSUE THREAD

**Issue by asigalov61** [asigalov61/Amazing-GPT2-Piano#1]
Here is the error:

If someone can help, I will be grateful. Thank you.

Last line of code (lol)

midi.write_midifile("output.mid", pattern)

Produces:

AssertionError                            Traceback (most recent call last)
<ipython-input-44-035ae5d574a0> in <module>()
----> 1 midi.write_midifile("output.mid", pattern)

4 frames
/usr/local/lib/python3.6/dist-packages/midi/fileio.py in write_midifile(midifile, pattern)
    167     if type(midifile) in (str, str):
    168         with open(midifile, 'wb') as out:
--> 169             return write_midifile(out,pattern)
    170     writer = FileWriter(midifile)
    171     return writer.write(pattern)

/usr/local/lib/python3.6/dist-packages/midi/fileio.py in write_midifile(midifile, pattern)
    169             return write_midifile(out,pattern)
    170     writer = FileWriter(midifile)
--> 171     return writer.write(pattern)
    172 
    173 def read_midifile(midifile):

/usr/local/lib/python3.6/dist-packages/midi/fileio.py in write(self, pattern)
    103         self.write_file_header(pattern,len(pattern))
    104         for track in pattern:
--> 105             self.write_track(track)
    106 
    107     def write_file_header(self, pattern, length=None):

/usr/local/lib/python3.6/dist-packages/midi/fileio.py in write_track(self, track)
    120         buf = bytearray(b'0'*hlen)
    121         for event in track:
--> 122             buf.extend(self.encode_midi_event(event))
    123         buf[:hlen] = self.encode_track_header(len(buf)-hlen)
    124         self.file.write(buf)

/usr/local/lib/python3.6/dist-packages/midi/fileio.py in encode_midi_event(self, event)
    139         ret = bytearray()
    140         #assert hasattr(event,'tick'), event
--> 141         assert isinstance(event.tick,int), event.tick
    142         ret.extend(write_varlen(event.tick))
    143         # is the event a MetaEvent?

AssertionError: 20

**Comment by asigalov61** [comment]
Resolved by installing latest and greatest dependencies. --update on all did the trick. And I've also added a few. Thank you, Alex!

**Comment by ravi-annaswamy** [comment]
great!

**Comment by asigalov61** [comment]
Thanks :)))
